services:
  gitea:
    image: gitea/gitea:1.25
    container_name: gitea
    restart: always
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: ${DB_HOST}
      GITEA__database__NAME: ${DB_NAME}
      GITEA__database__USER: ${DB_USER}
      GITEA__database__PASSWD: ${DB_PASSWD}
      USER_UID: "1000"
      USER_GID: "1000"
      USER: git
      GITEA_CUSTOM: /data/gitea
    volumes:
      - /mnt/user/appdata/gitea:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3912:3000"
    networks:
      - frontend
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitea-https.rule: "Host(`${DOMAIN}`)"
      traefik.http.routers.gitea-https.entrypoints: "websecure"
      traefik.http.routers.gitea-https.tls: "true"
      traefik.http.routers.gitea-https.service: "gitea-svc"
      traefik.http.services.gitea-svc.loadBalancer.server.port: "3000"
      com.centurylinklabs.watchtower.enable: "true"

networks:
  frontend:
    external: true
